### PR TITLE
Fix generated wheel naming and platform metadata as -any

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

In https://github.com/conda-forge/yasa-feedstock/pull/11 I get a `pip check` failure:
```
soundfile 0.12.1 is not supported on this platform
```
which suggests to me that something is wrong with the metadata somehow. Adding a `pip check` here to see if the problem also shows up.

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
Ohhh there is a `max_py_ver` of 37 so it *should* be listed as incompatible. I'm going to remove those hoping it's the right thing to do (I assume that isn't the max version anymore???) and see if it helps

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
Okay, successfully replicated the problem:
```
+ python -c 'import soundfile; print(soundfile._libname)'
$PREFIX/lib/libsndfile.so.1
+ pip check -vvv
soundfile 0.12.1 is not supported on this platform
```
Looks like there is something fishy with the metadata for this package

**Comment by larsoner** [comment]
@bmcfee any ideas?

**Comment by bmcfee** [comment]
Nothing immediately comes to mind as to why this would suddenly start failing.  Last time I was in the guts of this I noted some fishiness with the test here: https://github.com/conda-forge/pysoundfile-feedstock/pull/17#issuecomment-1431269106 ; could be worth probing into that a little more?

**Comment by larsoner** [comment]
> Nothing immediately comes to mind as to why this would suddenly start failing

Given that `pip check` wasn't being run before, it's not clear to me when it started failing, or if it has always failed but it's just now being noticed. I only noticed because `yasa` uses `wfdb` (who also does not `pip check`), and `wfdb` just updated their version to a newer one that requires `soundfile`.

**Comment by larsoner** [comment]
Okay looking at the build log, it looks like the build command `python -m pip install . --no-deps -vv` internally now calls a `bdist_wheel`. And you have set `PYSOUNDFILE_PLATFORM=win32` so it should trigger all the tag business from the upstream [`setup.py`](https://github.com/bastibe/python-soundfile/blob/44d2f7a25d220f7fd6ea316ce962f8c12c9d50b4/setup.py#L79) so we get a `win_amd64` in the filename:
```
2024-12-02T16:15:41.8583825Z   Created wheel for soundfile: filename=soundfile-0.12.1-py2.py3-none-win_amd64.whl size=24055 sha256=dac71c7e47f8246ae7c8b88f57d8d0506c1e8b1f6628cb74be25a4595eb1d6da
```
I wouldn't be surprised if this caused `pip` to say "this is for Windows only" in its metadata.

*EDIT: I checked locally the `soundfile-0.12.1-py2.py3-none-win_amd64.whl` that is produced and indeed it does:*
```
$ cat soundfile-0.12.1.dist-info/WHEEL 
Wheel-Version: 1.0
Generator: bdist_wheel (0.43.0)
Root-Is-Purelib: true
Tag: py2-none-win_amd64
Tag: py3-none-win_amd64
```

I'll try setting the platform to `any` which I *think* should cause it to create a wheel that is named to work on all platforms... :crossed_fingers:

**Comment by larsoner** [comment]
... this will conflict with the notes about https://github.com/bastibe/python-soundfile/pull/288 but it will at least tell us if it's the problem.

**Comment by larsoner** [comment]
Okay, looks like that's the problem.

Should this package really be `noarch` given that the wheels are platform-specific?

**Comment by bmcfee** [comment]
> Should this package really be `noarch` given that the wheels are platform-specific?

Probably not - I don't know how that ended up being the case originally.

**Comment by larsoner** [comment]
Okay, finally green :rocket: (after a few dozen failed attempts :sweat:)

The trick was to patch out the `cmdclass` stuff where the wheel name was changed. I tried (for a long time!) to use the PYSOUNDFILE_* env vars instead, and maybe could have gotten it working by patching the `manylinux_` in `setup.py` to be high enough that it wasn't overwritten by `pip` (at least I think that's what was happening!) when creating the wheel name. But this seemed much more complicated and fragile than just letting `pip` do what it does by default.

Ready for review/merge from my end:

1. First commit makes it arch-specific and improves the tests (tests lib access and `pip check`s), only real changes in five files in `recipe/*` and the root-level `conda-forge.yml`.
2. Second commit is a local rerender and results in the other ~35 files changed.
3. Third commit fixes the Windows build script to have the env var it needs (I had accidentally removed it), and adds a test that WAV file info can actually be read by the library from disk (might catch the need for the env var but I'm not sure really...)

**Comment by bmcfee** [comment]
Wow, thanks for the mega PR on this!  It all looks good to me, but I also don't have too much experience with all the build systems involved.  It's probably good if @wolfv can also give it a quick look over.

It looks like we have all the same platform coverage as the upstream libsndfile feedstock, so I don't anticipate moving from noarch to cause any dependency chain problems.

**Comment by mgeier** [comment]
> > Should this package really be `noarch` given that the wheels are platform-specific?
> 
> Probably not - I don't know how that ended up being the case originally.

The wheels always have been platform-specific, because they contain platform-specific binaries for libsndfile.

However, the conda package didn't contain any binaries, therefore it didn't need to be platform-specific. It just depended on the `libsndfile` package, which contains the platform-specific binaries.

**Comment by larsoner** [comment]
> However, the conda package didn't contain any binaries, therefore it didn't need to be platform-specific. It just depended on the libsndfile package, which contains the platform-specific binaries.

... except that there is some code in there to add a definition for something that is windows-specific when you're on Windows. If you're okay having that in all the wheels (even where it's unusable) I could see if it's possible to keep it noarch (I guess that's what was being done before?). It's a pain to get the wheel naming right but I think it might be doable.

**Comment by mgeier** [comment]
> ... except that there is some code in there to add a definition for something that is windows-specific when you're on Windows.

You mean this definition?

    SNDFILE* sf_wchar_open (const wchar_t *wpath, int mode, SF_INFO *sfinfo) ;

I don't think that hurts on non-Windows systems. You can define whatever function signatures in there. As long as they are not used, they don't have to exist in the actual library.

That's why `win32` is selected here:

https://github.com/conda-forge/pysoundfile-feedstock/blob/c38db89b992ed0dd0973f8c8ccf564179ee17db6/recipe/meta.yaml#L18-L23

There's even an old unmerged PR that would avoid defining that environment variable: https://github.com/bastibe/python-soundfile/pull/288

**Comment by larsoner** [comment]
Okay changed it so it's now still `noarch` but the metadata makes it clear that's the case as well. Should be good to go!

**Comment by larsoner** [comment]
@bmcfee this one is a much smaller / less controversial change now, feel free to merge if you're happy

**Review by bmcfee — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
