### PR TITLE
Soundfile 0.12.1 release

### PR DESCRIPTION
**Pull request by bmcfee**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR updates the pysoundfile package to 0.12.0.  The main change from conda-forge's side is to increment the minimum libsndfile to 1.2.

### CODE REVIEW

**Comment by bmcfee** [comment]
I think this is good to go, but would appreciate a quick check from at least one other person.

The 0.12 release of this package mainly affects the wheel builds for pypi (as well as some minor compatibility changes for libsndfile 1.2), but there were some under-the-hood changes to how the libsndfile object is located and I'm not sure if that will cause a problem for the conda-forge package.

I expect that it's fine, but to be safe, I added a test line to the recipe that prints out the path to the detected object file.  This *should* correspond to the conda-forge build of libsndfile; since we're building the python package from the source distribution that doesn't include any precompiled binaries, there shouldn't be any conflicts.

The test output is currently:
```
export PREFIX=/home/conda/feedstock_root/build_artifacts/pysoundfile_1676462156916/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/pysoundfile_1676462156916/test_tmp
import: 'soundfile'
import: 'soundfile'
+ python -c 'import soundfile; print(soundfile._libname)'
$PREFIX/lib/libsndfile.so.1
+ exit 0
```
I'm a little surprised that the `$PREFIX` isn't being interpolated here, and I'm not 100% sure that this actually corresponds to the conda environment search path (and not something else constructed in the build process).  Confirmation on this would be much appreciated!

**Comment by bmcfee** [comment]
We might actually want to skip 0.12.0 in conda-forge and go to 0.12.1 (when it's released) due to this issue: https://github.com/bastibe/python-soundfile/issues/369

**Comment by bastibe** [comment]
Thank you for noticing this bug, I will push an update immediately.

I just released 0.12.1 which should fix this bug.

**Comment by bmcfee** [comment]
To check the above, I created a pr #20 using the old version of python-soundfile (0.11) and adding the `_libname` test as done here.  Everything looks the same, so I'm pretty confident this is good to merge.

**Pull request merged**
