### PR TITLE
updated for 0.11.0 release

### PR DESCRIPTION
**Pull request by bmcfee**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Note: I haven't tried building this locally from source, just updating the recipe for the new release.

### CODE REVIEW

**Comment by bmcfee** [comment]
Another issue to note here: at some point, the package renamed from `pysoundfile` to `soundfile` on pypi. Would it be possible / make sense to rename the conda package accordingly?  (I've left it as `pysoundfile` for now.)

**Comment by bmcfee** [comment]
Another note: to get the full benefits of this new release, the `libsndfile` package should be updated as well.  This ties into a long-outstanding PR I had over there https://github.com/conda-forge/libsndfile-feedstock/pull/25 which is in turn blocked by some windows build stuff that I'm not able to work on.

**Comment by bmcfee** [comment]
Ok, I believe this one is unblocked now too.  I still think we should discuss renaming the conda package, but that can be a separate issue from this release update.

**Comment by bmcfee** [comment]
(tagging @wolfv while we're still on the topic of sndfile business :grin: )

**Comment by wolfv** [comment]
Awesome job @bmcfee !

**Pull request merged**
