### PR TITLE
libsndfile is available just for osx and linux

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
``libsndfile`` is available just for ``osx`` and ``linux``. To return it to be ``noarch`` I think we will need to build ``libsndfile`` for ``win`` as well

**Comment by marcelotrevisani** [comment]
cc: @scopatz

**Comment by scopatz** [comment]
I think this can be noarch python, though.  As long as all of the dependencies are available, it should install. This doesn't contain any compiled code.

**Comment by marcelotrevisani** [comment]
> I think this can be noarch python, though. As long as all of the dependencies are available, it should install. This doesn't contain any compiled code.

The project itself does not contain any compiled code indeed. However, it relies on ``libsndfile`` which is a compiled project and it is not available on ``conda-forge`` for ``windows``.
The problem is if someone tries to install this on windows the person will have a broken package installed, to be honest, it will not be installed because ``conda`` will complain about ``libsndfile``.

So we have a broken tree of dependencies in my humble opinion, it may cause some problems.
Because someone might add this package as a dependency of another one and the person will think that the windows package is fine as a matter of fact it is not...

For me, it seems to be incongruent, because if you run conda or if you go to the anaconda cloud you will think that is ok to be installed on ``windows``

**Comment by ocefpaf** [comment]
> I think this can be noarch python, though. As long as all of the dependencies are available, it should install. This doesn't contain any compiled code.

`noarch` is not only about compiled `code` but also about any platform specific characteristic of a package. [Outsourcing the final missing dependency error to `conda` gives a really bad Windows experience for end users.](https://twitter.com/astrofrog/status/1188802721207504903)

**Comment by scopatz** [comment]
It seems like conda should have better messaging about this then. I don't see a reason we should have arch'd packages when noarch is feasible.  There are many noarch packages that we have that only install on a particular platform.  I think if we want to have a broader conversation about this, that would be better than trying to resolve it in this PR

**Comment by ocefpaf** [comment]
@marcelotrevisani there is not a lot of sympathy for Windows users. Sorry :-(

**Comment by marcelotrevisani** [comment]
I just think that might frustrate some people (especially windows users)
Closing it then

**Comment by ocefpaf** [comment]
> I just think that might frustrate some people (especially windows users)
> Closing it then

Yeah. I agree. There is something we can do to fix it but no will to do it here. Sorry.

**Pull request closed without merging**
